env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - prettier
rules:
  react/react-in-jsx-scope:
    - off
  react-hooks/rules-of-hooks:
    - warn
  react-hooks/exhaustive-deps:
    - warn
  prettier/prettier:
    - warn


